"""'车辆，架台，设备连接'

Revision ID: 0b90c8691518
Revises: 
Create Date: 2019-05-09 11:47:08.478272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b90c8691518'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carId', sa.String(length=32), nullable=False),
    sa.Column('carIp', sa.String(length=32), nullable=False),
    sa.Column('carPort', sa.String(length=32), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carinfo_carId'), 'carinfo', ['carId'], unique=False)
    op.create_index(op.f('ix_carinfo_carIp'), 'carinfo', ['carIp'], unique=False)
    op.create_index(op.f('ix_carinfo_carPort'), 'carinfo', ['carPort'], unique=False)
    op.create_table('connectdevice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.String(length=32), nullable=False),
    sa.Column('platform_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectdevice_car_id'), 'connectdevice', ['car_id'], unique=False)
    op.create_index(op.f('ix_connectdevice_platform_id'), 'connectdevice', ['platform_id'], unique=False)
    op.create_table('platforminfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platformId', sa.String(length=32), nullable=False),
    sa.Column('platformIp', sa.String(length=32), nullable=False),
    sa.Column('platformPort', sa.String(length=32), nullable=False),
    sa.Column('parseAdderss', sa.String(length=32), nullable=False),
    sa.Column('parsePort', sa.String(length=32), nullable=False),
    sa.Column('platformNum', sa.String(length=32), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforminfo_parseAdderss'), 'platforminfo', ['parseAdderss'], unique=False)
    op.create_index(op.f('ix_platforminfo_parsePort'), 'platforminfo', ['parsePort'], unique=False)
    op.create_index(op.f('ix_platforminfo_platformId'), 'platforminfo', ['platformId'], unique=False)
    op.create_index(op.f('ix_platforminfo_platformIp'), 'platforminfo', ['platformIp'], unique=False)
    op.create_index(op.f('ix_platforminfo_platformNum'), 'platforminfo', ['platformNum'], unique=False)
    op.create_index(op.f('ix_platforminfo_platformPort'), 'platforminfo', ['platformPort'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platforminfo_platformPort'), table_name='platforminfo')
    op.drop_index(op.f('ix_platforminfo_platformNum'), table_name='platforminfo')
    op.drop_index(op.f('ix_platforminfo_platformIp'), table_name='platforminfo')
    op.drop_index(op.f('ix_platforminfo_platformId'), table_name='platforminfo')
    op.drop_index(op.f('ix_platforminfo_parsePort'), table_name='platforminfo')
    op.drop_index(op.f('ix_platforminfo_parseAdderss'), table_name='platforminfo')
    op.drop_table('platforminfo')
    op.drop_index(op.f('ix_connectdevice_platform_id'), table_name='connectdevice')
    op.drop_index(op.f('ix_connectdevice_car_id'), table_name='connectdevice')
    op.drop_table('connectdevice')
    op.drop_index(op.f('ix_carinfo_carPort'), table_name='carinfo')
    op.drop_index(op.f('ix_carinfo_carIp'), table_name='carinfo')
    op.drop_index(op.f('ix_carinfo_carId'), table_name='carinfo')
    op.drop_table('carinfo')
    # ### end Alembic commands ###
