"""'model重建'

Revision ID: 5c768ed56301
Revises: de501689db86
Create Date: 2019-05-23 11:10:47.194653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c768ed56301'
down_revision = 'de501689db86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appinfo', sa.Column('deviceId', sa.String(length=32), nullable=True))
    op.add_column('appinfo', sa.Column('type', sa.String(length=1), nullable=True))
    op.create_index(op.f('ix_appinfo_deviceId'), 'appinfo', ['deviceId'], unique=False)
    op.create_index(op.f('ix_appinfo_type'), 'appinfo', ['type'], unique=False)
    op.alter_column('carinfo', 'online',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_index('ix_carinfo_carId', table_name='carinfo')
    op.create_index(op.f('ix_carinfo_carId'), 'carinfo', ['carId'], unique=True)
    op.drop_index('ix_carinfo_carPort', table_name='carinfo')
    op.drop_column('carinfo', 'carPort')
    op.add_column('platforminfo', sa.Column('platformName', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_platforminfo_platformName'), 'platforminfo', ['platformName'], unique=False)
    op.drop_index('ix_platforminfo_platformId', table_name='platforminfo')
    op.create_index(op.f('ix_platforminfo_platformId'), 'platforminfo', ['platformId'], unique=True)
    op.drop_index('ix_platforminfo_parseAdderss', table_name='platforminfo')
    op.drop_index('ix_platforminfo_platformNum', table_name='platforminfo')
    op.drop_index('ix_platforminfo_platformPort', table_name='platforminfo')
    op.drop_column('platforminfo', 'platformPort')
    op.drop_column('platforminfo', 'parseAdderss')
    op.drop_column('platforminfo', 'platformNum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforminfo', sa.Column('platformNum', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('platforminfo', sa.Column('parseAdderss', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('platforminfo', sa.Column('platformPort', mysql.VARCHAR(length=32), nullable=False))
    op.create_index('ix_platforminfo_platformPort', 'platforminfo', ['platformPort'], unique=False)
    op.create_index('ix_platforminfo_platformNum', 'platforminfo', ['platformNum'], unique=False)
    op.create_index('ix_platforminfo_parseAdderss', 'platforminfo', ['parseAdderss'], unique=False)
    op.drop_index(op.f('ix_platforminfo_platformId'), table_name='platforminfo')
    op.create_index('ix_platforminfo_platformId', 'platforminfo', ['platformId'], unique=False)
    op.drop_index(op.f('ix_platforminfo_platformName'), table_name='platforminfo')
    op.drop_column('platforminfo', 'platformName')
    op.add_column('carinfo', sa.Column('carPort', mysql.VARCHAR(length=32), nullable=False))
    op.create_index('ix_carinfo_carPort', 'carinfo', ['carPort'], unique=False)
    op.drop_index(op.f('ix_carinfo_carId'), table_name='carinfo')
    op.create_index('ix_carinfo_carId', 'carinfo', ['carId'], unique=False)
    op.alter_column('carinfo', 'online',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_index(op.f('ix_appinfo_type'), table_name='appinfo')
    op.drop_index(op.f('ix_appinfo_deviceId'), table_name='appinfo')
    op.drop_column('appinfo', 'type')
    op.drop_column('appinfo', 'deviceId')
    # ### end Alembic commands ###
