"""car添加车牌字段

Revision ID: a0bb7c605926
Revises: 0b90c8691518
Create Date: 2019-05-09 12:01:13.909559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0bb7c605926'
down_revision = '0b90c8691518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carinfo', sa.Column('carLicense', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_carinfo_carLicense'), 'carinfo', ['carLicense'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carinfo_carLicense'), table_name='carinfo')
    op.drop_column('carinfo', 'carLicense')
    # ### end Alembic commands ###
