"""添加用户表

Revision ID: c9d158c29add
Revises: a0bb7c605926
Create Date: 2019-05-10 10:18:16.705380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d158c29add'
down_revision = 'a0bb7c605926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('pwd', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userinfo_pwd'), 'userinfo', ['pwd'], unique=False)
    op.create_index(op.f('ix_userinfo_username'), 'userinfo', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userinfo_username'), table_name='userinfo')
    op.drop_index(op.f('ix_userinfo_pwd'), table_name='userinfo')
    op.drop_table('userinfo')
    # ### end Alembic commands ###
