"""添加创建时间字段create_at

Revision ID: d3f545bc2ffd
Revises: 5c768ed56301
Create Date: 2019-05-28 14:25:50.237706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f545bc2ffd'
down_revision = '5c768ed56301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carinfo', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('connectdevice', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('platforminfo', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_userinfo_username', table_name='userinfo')
    op.create_index(op.f('ix_userinfo_username'), 'userinfo', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userinfo_username'), table_name='userinfo')
    op.create_index('ix_userinfo_username', 'userinfo', ['username'], unique=False)
    op.drop_column('platforminfo', 'create_at')
    op.drop_column('connectdevice', 'create_at')
    op.drop_column('carinfo', 'create_at')
    # ### end Alembic commands ###
