"""新建appinfo表

Revision ID: de501689db86
Revises: c9d158c29add
Create Date: 2019-05-13 14:56:57.842589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de501689db86'
down_revision = 'c9d158c29add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_key', sa.String(length=32), nullable=True),
    sa.Column('app_secret', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appinfo_app_key'), 'appinfo', ['app_key'], unique=True)
    op.create_index(op.f('ix_appinfo_app_secret'), 'appinfo', ['app_secret'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appinfo_app_secret'), table_name='appinfo')
    op.drop_index(op.f('ix_appinfo_app_key'), table_name='appinfo')
    op.drop_table('appinfo')
    # ### end Alembic commands ###
